[workspace]
members = [
    "crates/astral",
    "crates/aurora",
    "crates/echo",
    "crates/eden",
    "crates/january",
    "crates/lumen",
    "crates/solstice",
    "crates/sonar",
    "crates/starlight",
]